version: "3.9"
services:
  redis:
    container_name: redis
    image: "redis/redis-stack"
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: ["redis-server", "/etc/redis/redis.conf"]
      
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  node:
    container_name: express
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run start"
    depends_on:
      - redis
    ports:
      - 8081:8081
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000